### ISSUE TITLE
starting "node app.js" giving error

### ISSUE THREAD

**Issue by minsoe** [pusher-community/pusher-realtime-chat-widget#21]
starting the "node app.js" is giving the following error. Maybe package.json is broken. I did call "npm install"

module.js:340
    throw err;
          ^
Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/.../GitHub/pusher-realtime-chat-widget/src/nodejs/app.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by zimbatm** [comment]
First you have to copy the `config_example.js` file to `config.js` and put your own credentials in it.
